---
# yamllint disable rule:line-length

- name: Make sure handlers are flushed immediately
  meta: flush_handlers

- name: Install patroni etcd
  package:
    name: etcd
    state: present
  tags: etcd, etcd_install

# FIXME: Don't keep the initial setup config for ever.
- name: Generate conf file "/etc/default/etcd"
  template:
    src: templates/etcd.conf.j2
    dest: /etc/default/etcd
  tags: etcd, etcd_conf

# The debian package autostarts and bootstraps a single node cluster even before
# we get to write that config above, so we need to stop, clean and start etcd.
# FIXME: This is a total hack and should not kill etcd every time we run
# ansible. Use a handler that listens on the etcd installation or something..
- name: Stop etcd service
  systemd:
    name: etcd
    state: stopped

- name: Recursively remove directory
  file:
    path: "{{ etcd_data_dir }}/default"
    state: absent

- name: Enable and start etcd service
  systemd:
    name: etcd
    enabled: true
    state: started

- name: Wait for port 2379 to become open on the host
  wait_for:
    port: 2379
    host: 127.0.0.1
    state: started
    timeout: 120
    delay: 10
  ignore_errors: false
  tags: etcd, etcd_start

- block:
    - name: Wait until the etcd cluster is healthy
      command: /usr/bin/etcdctl cluster-health
      environment:
        ETCDCTL_API: 2
      register: etcd_health_result
      run_once: true
      changed_when: false
      until: "'cluster is healthy' in etcd_health_result.stdout"
      retries: 10
      delay: 10
      ignore_errors: false

    - name: cluster health
      run_once: true
      debug:
        var: etcd_health_result.stdout_lines
  tags: etcd, etcd_start, etcd_status

...
